### ISSUE TITLE
Upgrade heap-0.6 to > 1.0+

### ISSUE THREAD

**Issue by jimstutt** [3of8/heap#2]
extractHeap in heap-1.0.\* has been deprecated in favor of view but is required in MidiIO.hs.

**Comment by pruvisto** [comment]
I don't really understand what it is that you want me to do. Are you saying I should reintroduce an extractHeap operation so that MidiIO works again?

**Comment by jimstutt** [comment]
Please ignore, somehow I posted here instead of in an email to the Euterpea maintainer. Apologies.

**Comment by pruvisto** [comment]
No worries. :)
