### ISSUE TITLE
Compile error with base < 4.6

### ISSUE THREAD

**Issue by hvr** [3of8/heap#3]
```
Configuring component lib from heap-1.0.3...
Preprocessing library heap-1.0.3...
[1 of 3] Compiling Data.Heap.Internal ( Data/Heap/Internal.hs, /tmp/matrix-worker/1496496621/dist-newstyle/build/x86_64-linux/ghc-7.4.2/heap-1.0.3/build/Data/Heap/Internal.o )

Data/Heap/Internal.hs:36:54:
    Module `Prelude' does not export `foldMap'
```

I've already revised the meta-data of the affected releases (so there's no immediate need for uploading a new release), see

 - https://hackage.haskell.org/package/heap-1.0.3/revisions/
 - https://hackage.haskell.org/package/heap-1.0.2/revisions/

And while at it, the following ones needed upper bounds tightened:

 - https://hackage.haskell.org/package/heap-1.0.1/revisions/
 - https://hackage.haskell.org/package/heap-1.0.0/revisions/

See also https://matrix.hackage.haskell.org/package/heap to get an overview of `heap`'s install-plan health

**Comment by pruvisto** [comment]
Thank you for taking care of this.

I am a bit confused; I have no idea what an ‘install plan’ is and what needs to be done about the heap package now.

**Comment by hvr** [comment]
@pruvisto the simplest way to address this, is to tighten the lower bound on `base` to `base >= 4.6` in the Git repo (just so if you ever release a new version of `heap` to Hackage the meta-data is correct right-away) if you don't care to restore compatibility with `base < 4.6`.

What I mean by "install plan" is simply the result of the cabal solver when you "cabal install" something; it involves determining (solving for) the set of dependencies, flag settings etc in order to build a package including all required dependencies while satisfying the all declared version constraints.
